name = "HaloPencils"
uuid = "7a0ce8e1-df09-4a8d-b862-9758701b5256"
authors = ["Chris Howland <c.j.howland@utwente.nl> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
